version: "3"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1001:1001
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "/home/aaron/music:/music:ro"
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true