version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_directives.conf:/etc/nginx/proxy_directives.conf
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true
