version: "3"

volumes:
  nextcloud:
  database:

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - config.env

  database:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    env_file:
      - config.env
