version: "3"

volumes:
  nextcloud:
  database:

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - config.env
    networks:
      - homelab
      - nextcloud-data-network

  database:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    env_file:
      - config.env
    networks:
      - nextcloud-data-network

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true
  nextcloud-data-network:
    driver: bridge
