version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - homelab

volumes:
  jenkins_home:

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true